apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-app
spec:
  template:
    spec:
      containers:
      - name: chatbot
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
data:
  ENVIRONMENT: "development"
  LOG_LEVEL: "DEBUG"
