apiVersion: apps/v1
kind: Deployment
metadata:
  name: multistage-app
spec:
  template:
    spec:
      containers:
      - name: multistage
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"