apiVersion: apps/v2
kind: Deployment
metadata:
  name: chatbot-app
spec:
  template:
    spec:
      containers:
      - name: chatbot
        image: 145023123305.dkr.ecr.us-east-1.amazonaws.com/fcj-chatbot:1f9b8cafe4018f436a53eeca019de04c8306e37f
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
