apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-app
spec:
  selector:
    matchLabels:
      app: chatbot-app
  template:
    metadata:
      labels:
        app: chatbot-app
    spec:
      containers:
      - name: chatbot
        image: 145023123305.dkr.ecr.us-east-1.amazonaws.com/fcj-chatbot:1f9b8cafe4018f436a53eeca019de04c8306e37f
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config
data:
  ENVIRONMENT: "development"
  LOG_LEVEL: "DEBUG"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multistage-app
spec:
  selector:
    matchLabels:
      app: multistage-app
  template:
    metadata:
      labels:
        app: multistage-app
    spec:
      containers:
      - name: multistage
        image: 145023123305.dkr.ecr.us-east-1.amazonaws.com/fcj-chatbot:0739900c3242d54aaf35e2ba679eb339f6bbcb94
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
